excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://DougThompson1976.github.io
title: Simple Life Questions
tagline: Leverage Computers Beneficially
description: A journey to help people using science, literature, and fun!
paginate: 5